### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ed20651 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ed20651346d59237b6c1eecf37e1b67bae4299b2 with merge 01e29371b307c09a9fc0107bcef08fefacde62d5...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-rt-ld/builds/342770822?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 01e29371b307c09a9fc0107bcef08fefacde62d5 to master...

**Pull request merged**
